# SPDX-FileCopyrightText: 2024-2026 Subhadip Mitra <contact@subhadipmitra.com>
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-iso8583sim-Commercial

"""Generate the Python API reference pages (docs/api/**.mdx) from the package docstrings.

Run from the repository root:

    python scripts/generate_api_docs.py          # write the pages
    python scripts/generate_api_docs.py --check  # exit 1 if the committed pages are stale

Docstrings are parsed statically with griffe (Google style), so modules with optional
dependencies (web, mcp, llm providers) are documented without installing those extras.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import griffe

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "api"

# subhadipmitra@: One page per module, grouped as they appear in the sidebar. The title is
# what the sidebar shows; the full module path is in the page heading.
GROUPS: dict[str, list[tuple[str, str]]] = {
    "Core": [
        ("iso8583sim.core.types", "Types"),
        ("iso8583sim.core.parser", "Parser"),
        ("iso8583sim.core.builder", "Builder"),
        ("iso8583sim.core.validator", "Validator"),
        ("iso8583sim.core.network_rules", "Network rules"),
        ("iso8583sim.core.emv", "EMV"),
        ("iso8583sim.core.codes", "Codes"),
        ("iso8583sim.core.describe", "Describe"),
        ("iso8583sim.core.convert", "Convert"),
        ("iso8583sim.core.samples", "Samples"),
        ("iso8583sim.core.pool", "Pool"),
        ("iso8583sim.core.mti", "MTI"),
    ],
    "Security": [
        ("iso8583sim.security.pinblock", "PIN blocks"),
        ("iso8583sim.security.mac", "MACs"),
    ],
    "Wire formats": [
        ("iso8583sim.wire.format", "WireFormat"),
        ("iso8583sim.wire.codec", "Encode and decode"),
    ],
    "Networking": [
        ("iso8583sim.net.framing", "Framing"),
        ("iso8583sim.net.client", "Client"),
        ("iso8583sim.net.host", "Mock host"),
        ("iso8583sim.net.load", "Load testing"),
    ],
    "LLM": [
        ("iso8583sim.llm.base", "Base"),
        ("iso8583sim.llm.explainer", "Explainer"),
        ("iso8583sim.llm.generator", "Generator"),
        ("iso8583sim.llm.providers", "Providers"),
    ],
    "Servers": [
        ("iso8583sim.mcp.server", "MCP server"),
        ("iso8583sim.web.app", "REST app"),
    ],
    "Demo": [("iso8583sim.demo", "Demo helpers")],
}

HEADER = "{/* Generated by scripts/generate_api_docs.py from the docstrings. Do not edit by hand. */}"


def page_path(module: str) -> Path:
    """iso8583sim.core.parser -> docs/api/core/parser.mdx; iso8583sim.demo -> docs/api/demo.mdx"""
    parts = module.split(".")[1:]
    return OUT.joinpath(*parts).with_suffix(".mdx")


# MDX escaping


def escape_mdx(text: str) -> str:
    """Escape characters MDX would read as JSX, outside code spans and fenced code."""
    # subhadipmitra@: MDX treats { } as expressions and < as the start of a tag. Docstrings
    # contain both in prose (e.g. {"match": {...}} or <subdomain>), so escape them, but leave
    # code untouched, where they are literal.
    out = []
    for block in re.split(r"(```.*?```)", text, flags=re.S):
        if block.startswith("```"):
            out.append(block)
            continue
        pieces = re.split(r"(`[^`]*`)", block)
        for i, piece in enumerate(pieces):
            if i % 2 == 0:
                piece = piece.replace("{", "\\{").replace("}", "\\}").replace("<", "&lt;")
            pieces[i] = piece
        out.append("".join(pieces))
    return "".join(out)


def attr(value: str) -> str:
    """Quote a value for a JSX attribute."""
    return json.dumps(value)


def doctest_to_code(text: str) -> str:
    """Turn >>> example blocks into fenced Python code."""
    lines, out, block = text.splitlines(), [], []
    for line in lines + [""]:
        if line.lstrip().startswith((">>>", "...")) and (line.lstrip().startswith(">>>") or block):
            block.append(re.sub(r"^\s*(>>>|\.\.\.) ?", "", line))
            continue
        if block:
            out += ["```python", *block, "```"]
            block = []
        out.append(line)
    return "\n".join(out).rstrip()


# Rendering


def annotation(obj: object) -> str:
    return str(obj) if obj is not None else ""


def signature(fn: griffe.Function, name: str | None = None) -> str:
    params = []
    for p in fn.parameters:
        if p.name in ("self", "cls"):
            continue
        text = p.name
        if p.kind is griffe.ParameterKind.var_positional:
            text = "*" + text
        elif p.kind is griffe.ParameterKind.var_keyword:
            text = "**" + text
        if p.annotation is not None:
            text += f": {p.annotation}"
        if p.default is not None and p.kind not in (
            griffe.ParameterKind.var_positional,
            griffe.ParameterKind.var_keyword,
        ):
            text += f" = {p.default}"
        params.append(text)
    returns = f" -> {fn.returns}" if fn.returns is not None and fn.name != "__init__" else ""
    prefix = "async def " if "async" in fn.labels else "def "
    one_line = f"{prefix}{name or fn.name}({', '.join(params)}){returns}"
    if len(one_line) <= 88:
        return one_line
    body = ",\n".join(f"    {p}" for p in params)
    return f"{prefix}{name or fn.name}(\n{body},\n){returns}"


def sections(obj: griffe.Object) -> list:
    return obj.docstring.parse("google") if obj.docstring else []


def render_docstring(obj: griffe.Object, fn: griffe.Function | None = None) -> list[str]:
    """Render text, parameters, returns, raises and examples of a docstring."""
    out: list[str] = []
    params_by_name = {p.name: p for p in fn.parameters} if fn else {}
    for sec in sections(obj):
        kind = sec.kind.value
        if kind == "text":
            out.append(escape_mdx(doctest_to_code(sec.value)))
        elif kind in ("parameters", "other parameters"):
            out.append("**Parameters**")
            for p in sec.value:
                sig_param = params_by_name.get(p.name)
                type_ = annotation(p.annotation) or (annotation(sig_param.annotation) if sig_param else "")
                default = sig_param.default if sig_param is not None else None
                props = [f"name={attr(p.name)}"]
                if type_:
                    props.append(f"type={attr(type_)}")
                if (
                    default is None
                    and sig_param is not None
                    and sig_param.kind.value
                    not in (
                        "variadic positional",
                        "variadic keyword",
                    )
                ):
                    props.append("required")
                elif default is not None:
                    props.append(f"default={attr(str(default))}")
                out.append(f"<ResponseField {' '.join(props)}>\n  {escape_mdx(p.description or '')}\n</ResponseField>")
        elif kind == "returns":
            for r in sec.value:
                type_ = annotation(r.annotation) or (annotation(fn.returns) if fn else "")
                props = f'name="Returns" type={attr(type_)}' if type_ else 'name="Returns"'
                out.append(f"<ResponseField {props}>\n  {escape_mdx(r.description or '')}\n</ResponseField>")
        elif kind == "raises":
            out.append("**Raises**")
            out.append("\n".join(f"- `{r.annotation}`: {escape_mdx(r.description or '')}" for r in sec.value))
        elif kind == "examples":
            out.append("**Example**")
            for sub_kind, value in sec.value:
                if sub_kind.value == "examples":
                    out.append("```python\n" + re.sub(r"^(>>>|\.\.\.) ?", "", value, flags=re.M) + "\n```")
                else:
                    out.append(escape_mdx(value))
        elif kind == "attributes":
            out.append("**Attributes**")
            for a in sec.value:
                props = [f"name={attr(a.name)}"]
                if a.annotation:
                    props.append(f"type={attr(annotation(a.annotation))}")
                out.append(f"<ResponseField {' '.join(props)}>\n  {escape_mdx(a.description or '')}\n</ResponseField>")
        elif kind == "admonition":
            # subhadipmitra@: Google-style headings griffe doesn't know (a singular
            # "Example:", "Note:", "Warning:") arrive as admonitions. Examples become code,
            # everything else a callout.
            label = str(sec.value.annotation or sec.title or "note").lower()
            text = sec.value.description or ""
            if label.startswith("example"):
                out.append("**Example**")
                out.append(escape_mdx(doctest_to_code(text)))
            else:
                component = {"warning": "Warning", "tip": "Tip", "important": "Warning"}.get(label, "Note")
                out.append(f"<{component}>\n{escape_mdx(doctest_to_code(text))}\n</{component}>")
        else:
            out.append(escape_mdx(str(sec.value)))
    return out


def is_public(name: str) -> bool:
    return not name.startswith("_")


def own_members(obj: griffe.Object) -> list[griffe.Object]:
    """Public members defined in this object (not re-exports)."""
    return [m for name, m in obj.members.items() if is_public(name) and not m.is_alias]


def render_function(fn: griffe.Function, level: int = 3, name: str | None = None) -> list[str]:
    title = name or fn.name
    out = [f"{'#' * level} `{title}()`", f"```python\n{signature(fn, name)}\n```"]
    out += render_docstring(fn, fn)
    return out


def render_class(cls: griffe.Class) -> list[str]:
    out = [f"## `{cls.name}`"]
    if cls.bases:
        out.append("Bases: " + ", ".join(f"`{b}`" for b in cls.bases))
    is_enum = any(str(b).split(".")[-1] == "Enum" for b in cls.bases)
    init = cls.members.get("__init__")
    if init is not None and not init.is_alias and isinstance(init, griffe.Function) and not is_enum:
        out.append(f"```python\n{signature(init, cls.name).replace('def ', '', 1)}\n```")
    out += render_docstring(cls, init if isinstance(init, griffe.Function) else None)
    if isinstance(init, griffe.Function) and init.docstring and not is_enum:
        out += render_docstring(init, init)

    members = own_members(cls)
    if is_enum:
        rows = [m for m in members if isinstance(m, griffe.Attribute)]
        if rows:
            out.append("| Member | Value |\n|--------|-------|")
            out.append("\n".join(f"| `{m.name}` | `{m.value}` |" for m in rows))
        members = [m for m in members if not isinstance(m, griffe.Attribute)]

    for m in members:
        if isinstance(m, griffe.Function):
            if "property" in m.labels:
                out.append(f"### `{m.name}` <sup>property</sup>")
                if m.returns is not None:
                    out.append(f"Type: `{m.returns}`")
                out += render_docstring(m)
            else:
                out += render_function(m, 3)
        elif isinstance(m, griffe.Attribute) and m.docstring:
            out.append(f"### `{m.name}`")
            out += render_docstring(m)
    return out


def render_module(module: str, title: str, pkg: griffe.Module) -> str:
    mod = pkg[module.split(".", 1)[1]] if "." in module else pkg
    doc_sections = sections(mod)
    summary = ""
    if doc_sections and doc_sections[0].kind.value == "text":
        summary = doc_sections[0].value.strip().split("\n\n")[0].replace("\n", " ")
    front_matter = "\n".join(
        ["---", f"title: {json.dumps(title)}", f"description: {json.dumps(summary or module)}", "---"]
    )
    lines = [HEADER, f"`{module}`"]
    body = render_docstring(mod)
    # subhadipmitra@: The first paragraph is already the page description (shown under the
    # title), so drop it from the body instead of repeating it.
    if body and summary:
        first = body[0].split("\n\n", 1)
        if first[0].replace("\n", " ").strip() == escape_mdx(summary):
            body = ([first[1]] if len(first) > 1 else []) + body[1:]
    lines += body

    members = own_members(mod)
    classes = [m for m in members if isinstance(m, griffe.Class)]
    functions = [m for m in members if isinstance(m, griffe.Function)]
    for cls in classes:
        lines += render_class(cls)
    if functions:
        lines.append("## Functions")
        for fn in functions:
            lines += render_function(fn, 3)
    return front_matter + "\n\n" + "\n\n".join(line for line in lines if line).rstrip() + "\n"


def navigation() -> list[dict]:
    """The Python API part of the docs.json navigation."""
    return [
        {"group": group, "pages": [str(page_path(m).relative_to(DOCS).with_suffix("")) for m, _ in modules]}
        for group, modules in GROUPS.items()
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the committed pages are out of date")
    args = parser.parse_args()

    pkg = griffe.load("iso8583sim", search_paths=[str(ROOT)], docstring_parser="google")
    expected = {page_path(m): render_module(m, t, pkg) for ms in GROUPS.values() for m, t in ms}

    if args.check:
        stale = [p for p, text in expected.items() if not p.exists() or p.read_text() != text]
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)}")
        if stale:
            print("Run: python scripts/generate_api_docs.py")
        return 1 if stale else 0

    for p, text in expected.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    print(f"wrote {len(expected)} pages to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
